scalar-labs/scalar-admin

build.gradle

I faced the similar issue to the issue mentioned in the following article:
https://stackoverflow.com/questions/55484043/how-to-fix-could-not-find-policy-pick-first-with-google-tts-java-client
As this article says, after adding the `mergeServiceFiles` config for `shadowJar` in `build.gradle`, the issue is fixed.
Please take a look!

Add the mergeServiceFiles config for shadowJar

---

src/main/java/com/scalar/admin/AdminCommand.java

It seems to me that the current behavior with the `--wait-outstanding` option is unexpected.
The current behavior is as follows:
- When executing it without `--wait-outstanding` (the default behavior), it's waiting for termination of outstanding requests
- When executing it with `--wait-outstanding`, it's not waiting for termination of outstanding requests
It looks like the opposite behavior. The change in this PR will fix this issue.
Please take a look!

Fix the behavior with --wait-outstanding option

---

java/build.gradle

This PR upgrades the Java module scalar-admin to 1.2.0 for the new gRPC service `checkPaused`.
After this PR is merged and the module is released, we can upgrade the dependencies in scalar and scalrdb and update the server-side codes.

Upgrade version to 1.2.0

---

java/archive.gradle
java/build.gradle

This PR uses the `maven publish` plugin to replace the legacy `maven` plugin.

Use the maven publish plugin to publish scalar-admin correctly

---

node/package-lock.json

This PR upgrades the protobufjs dependency to fix CVE-2002-25878.
https://github.com/advisories/GHSA-g954-5hwp-pp24

Upgrade protobufjs for CVE-2022-25878

---

java/build.gradle

This PR revises the Java's module version to 2.0.0 since this version removes a gRPC service.

Upgrade Java's version to 2.0.0

---

java/Dockerfile

This PR upgrades the internal JRE Docker image to 1.1.4.

Upgrade the internal JRE Docker image to 1.1.4

---

.github/workflows/docker.yml

This PR creates a GitHub Actions workflow to release the `ghcr.io/scalar-labs/scalar-admin` image.

Add a new workflow to publish docker images

---

.github/workflows/maven-publish.yml

This PR creates a new GitHub Action workflow to publish the Java package to Maven Central Repository.
When a tag `java-x.y.z` is pushed, this workflow will be triggered.
Note: There's another workflow `docker` https://github.com/scalar-labs/scalar-admin/blob/main/.github/workflows/docker.yml to publish the Docker image to GitHub Package Registry.

Add a new workflow to publish the Java package

---

node/package-lock.json
node/package.json

This PR bumps the Node client package to 2.0.1.
This is to align the version to Java's version.
They need to be the same version in the current release policy.
Don't worry about the major version change.
Scalar Manager is the only client using it now.
I will push a tag `v2.0.1` to trigger the release workflows after this PR is merged.

Bump the Node client package version to the same version as Java

---

java/build.gradle

This PR upgrades log4j to version 2 for vulnerability fix.

Use log4j version 2

---

.github/workflows/maven-publish.yml

This PR fixes(?) an issue that I might indent command lines incorrectly.
I am not sure about the behavior of indenting them one more level so better to make them at the same level.

Fix the `maven-publish` workflow

---

java/src/main/java/com/scalar/admin/AdminCommand.java
java/src/main/java/com/scalar/admin/RequestCoordinator.java
java/src/test/java/com/scalar/admin/RequestCoordinatorTest.java

This PR enhances RequestCoordinator to support requesting by IP and port addresses.
The Node part will be in another PR.

Support requesting by ips and ports

---

java/Dockerfile

This PR updates the in-house JRE 8 Docker image to version 1.1.11 for CVE-2023-0286

Upgrade the in-house JRE 8 Docker image to version 1.1.11

---

java/Dockerfile

This PR upgrades the in-house JRE 8 Docker image to 1.1.12 for fixing CVE-2023-0361.

Upgrade the in-house JRE Docker image to 1.1.12

---

java/Dockerfile

This PR upgrades the in-house JRE Docker image to 1.1.14.

Upgrade the in-house JRE to 1.1.14

---

java/archive.gradle
java/build.gradle
node/package-lock.json
node/package.json

This PR revises the build system to fix two issues:
- The runtime class path was not included in the bin script
- The dependencies where not included in the BOM file (seems not caused by the `implementation` configuration)

Fix Gradle build system issues about classpath and dependencies

---

java/build.gradle
java/src/main/java/com/scalar/admin/AdminClient.java
java/src/main/java/com/scalar/admin/AdminCommand.java
java/src/main/java/com/scalar/admin/TlsRequestCoordinator.java

This PR implements the TLS support so that user can pass CA root certificate and override authority to build TLS gRPC connection to targets.
The command-line tool has three more options
- `--tls`
- `--ca-root-cert-path` and `--ca-root-cert-pem`
- `--override-authority`
N/A
- added a new class `TlsRequestCoordinator`
- made AdminClient able to setup SSL context when using netty
- Support TLS connection between scalar-admin clients and servers

Implement TLS support

---

.github/workflows/maven-publish.yml

This PR fixes a bug that put the keyring file in the `./gradle` folder.
This folder won't exist if we don't run Gradle in advance.
N/A
- revised one GitHub Actions workflow

Store the keyring in the /tmp

---

README.md
src/main/java/com/scalar/admin/AdminCommand.java

This PR adds more explanations on the `-s` option to stop users from using this option.
We should deprecate it in the future.
N/A
- revised README
- revised the CLI description

Revise the explanation for the `-s` option

---

src/main/java/com/scalar/admin/AdminCommand.java
src/main/resources/log4j.properties
src/main/resources/log4j2.properties

This PR adds a warning message when the users use the `-s` option. This is advised in #50 
#50 
- remove the old log4j properties and add the log4j2 properties
- added new warning message

Add a warning message for `-s` option

---

build.gradle

This PR fixes CVE-2024-25638 by bumping up the `dnsjava` library to `3.6.1`.
N/A
- Bumped up the `dnsjava` library to `3.6.1`.
N/A

Fix CVE-2024-25638

---

build.gradle

This PR bumps up the Protocol Buffers and gRPC libs to `3.24.4` and `1.66.0`.
N/A
- Bumped up the Protocol Buffers and gRPC libs to `3.24.4` and `1.66.0`
N/A

Bump Protocol Buffers and gRPC libs
